# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11AvzWNoTnEccN0Vb_7PHE62q_Jwt6iZI
"""

"""!pip install streamlit
!pip install openai
!pip install pytube`"""

import streamlit as st
from video_generator import video_tab
from chatbot_exam import exam_tab
from audio_transcriber import transcriber_tab

st.set_page_config(page_title="AI Narrator + Exam Bot", layout="wide")

tab = st.sidebar.radio("Choose Tool", ["🎬 Narrated Video", "🧪 Exam Chatbot", "🎙️ Audio Transcriber"])

if tab == "🎬 Narrated Video":
    video_tab()
elif tab == "🧪 Exam Chatbot":
    exam_tab()
elif tab == "🎙️ Audio Transcriber":
    transcriber_tab()
