# -*- coding: utf-8 -*-
"""audio_transcriber.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IvkWkPzVDRf2zxeXwGc67Zh5VHS18qXU
"""

!pip install streamlit

import streamlit as st
from utils.whisper_transcriber import transcribe_audio_whisper

def transcriber_tab():
    st.header("🎙️ Whisper Audio Transcriber")

    audio_file = st.file_uploader("Upload an audio file (MP3/WAV/M4A)", type=["mp3", "wav", "m4a"])

    if audio_file and st.button("📝 Transcribe"):
        with st.spinner("Transcribing with Whisper..."):
            result = transcribe_audio_whisper(audio_file)
        st.text_area("📄 Transcribed Text", result, height=250)