# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w4oLOxrnFmA5niVpC-b-7V_TmsJjVwuX
"""

!pip install streamlit

import streamlit as st

def exam_tab():
    st.header("🧠 Exam Chatbot")

    question = st.text_input("Ask your question:")
    correct_answer = st.text_input("Expected answer (for scoring):")

    if st.button("Submit"):
        if not question or not correct_answer:
            st.warning("Please enter both question and answer.")
            return

        # Simulated student answer (in real use: integrate LLM)
        student_answer = "Sample AI Answer"

        st.write("🗣️ Student Answer:", student_answer)

        # Simple scoring logic
        score = 100 if correct_answer.lower() in student_answer.lower() else 0
        st.metric(label="Score", value=f"{score}%")