# -*- coding: utf-8 -*-
"""extract_doc.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q_cILucT6KQT54HjaxfkWsZQO6_Cp9xD
"""

"""!pip install python-docx
!pip install python-pptx
!pip install pillow"""

from docx import Document
from pptx import Presentation
from PIL import Image
import io

def extract_text_from_docx(file):
    doc = Document(file)
    return "\n".join([p.text for p in doc.paragraphs])

def extract_text_from_pptx(file):
    prs = Presentation(file)
    text = ""
    for slide in prs.slides:
        for shape in slide.shapes:
            if hasattr(shape, "text"):
                text += shape.text + "\n"
    return text

def load_image(file):
    return Image.open(file)
