# -*- coding: utf-8 -*-
"""tts_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WYIvapMD7DR7t0B_R23IQWMVQlrsWF_8
"""

"""!pip install gTTS"""

from gtts import gTTS
import tempfile
import os

def generate_audio_gtts(text, lang="en"):
    tts = gTTS(text=text, lang=lang)
    out_path = tempfile.mktemp(suffix=".mp3")
    tts.save(out_path)
    return out_path
