# -*- coding: utf-8 -*-
"""video_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-4GZplB0P-VWrK_Yy4BFBAnQczhho8Um
"""

"""!pip install moviepy
!pip install pillow
!pip install ffmpeg"""

from PIL import Image, ImageDraw, ImageFont
import tempfile
import os
from moviepy.editor import ImageClip, AudioFileClip

def split_text_into_chunks(text, max_chars=300):
    return [text[i:i+max_chars] for i in range(0, len(text), max_chars)]

def generate_slide_image(text):
    img = Image.new("RGB", (1280, 720), color=(255, 255, 255))
    draw = ImageDraw.Draw(img)
    font = ImageFont.load_default()
    draw.text((50, 50), text, fill=(0, 0, 0), font=font)
    path = tempfile.mktemp(suffix=".png")
    img.save(path)
    return path

def create_video_with_audio(image_path, audio_path, output_path):
    audio_clip = AudioFileClip(audio_path)
    duration = audio_clip.duration

    image_clip = ImageClip(image_path).set_duration(duration).set_audio(audio_clip)
    image_clip.write_videofile(output_path, fps=24)

