# -*- coding: utf-8 -*-
"""whisper_transcriber.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ftiz-uwABc-Mv5dJBvV3ZB1o0KasgKh9
"""

"""!pip install openai"""

import openai
import tempfile

def transcribe_audio_whisper(file) -> str:
    openai.api_key = os.getenv("sk-1234567890abcdef1234567890abcdef12345678")
    with tempfile.NamedTemporaryFile(delete=False, suffix=".mp3") as temp_audio:
        temp_audio.write(file.read())
        temp_audio_path = temp_audio.name

    with open(temp_audio_path, "rb") as audio_file:
        transcript = openai.Audio.transcribe("whisper-1", audio_file)
        return transcript["text"]
